### ISSUE TITLE
Pikakirjoitus ei päivity muokkaa-näkymään? 

### ISSUE THREAD

**Issue by teemuoksanen** [luomus/lintuasemasovellus#45]
https://drive.google.com/file/d/1e_MS4GLZxjv3aTz_FRC3mlhpPmG6yg33/view?usp=sharing

**Comment by teemuoksanen** [comment]
Oletettavasti korjattu jo.

**Comment by LinAksel** [comment]
Ei toistu virhe mullakaan, merkitään korjatuksi
