### ISSUE TITLE
Päivänäkymän havaintotietotaulukkoon latausikoni

### ISSUE THREAD

**Issue by LinAksel** [luomus/lintuasemasovellus#50]
Kun päiviä kliksuttelee auki, haetaan tietoja havainnot-taulukkoon välillä jopa parin sekunnin ajan. Koska frontti ei kuitenkaan kerro mitenkään, haetaanko tietoa vielä, tulee välillä olo että sovellus on jäätynyt. Myös jos havaintoja ei ole (näin voi joskus käydä), näyttää tilanne identtiseltä, ja käyttäjän pitää arvuutella mitä on tapahtunut (onko tietoja, jäätyikö, haetaanko vielä..). Tähän voisi siis implementoida yksinkertaisen latauspalluran yms, jotta sovelluksen tilasta tulisi edes jotain tietoa käyttäjälle.

**Comment by sinikala** [comment]
En saanut yhtä merkittävää viivettä toteutumaan. Mutta vähintäänkin ilmoituksen siitä, että havaintoja ei ole olemassa, olisi varmastikin hyvä luoda.
