### ISSUE TITLE
Set up test version on Rahti 2

### ISSUE THREAD

**Issue by mikkohei13** [luomus/lintuasemasovellus#76]

**Comment by wkmor1** [comment]
How many/much resources (cpu's and mem) will this need? Might need to put in a quota increase request with CSC

**Comment by aorin** [comment]
The Rahti 1 doesn't seem to show how much resources it's using currently but I would think it doesn't require much

**Comment by wkmor1** [comment]
Yeah Rahti 1 was useless for seeing how much resources was being used. It made the migration a nightmare.

On Rahti 2 we currently have a buffer of 5 CPU and 20gig of mem.
We need to maintain a buffer of at least 3cpu and 14gig of mem so that all the scheduled cronjobs will run.

**Comment by aorin** [comment]
The app can be found here: https://lintuasema-dev.2.rahtiapp.fi/#/
It seems to use very little resources (500m cpu and 1Gi memory)

**Comment by wkmor1** [comment]
I notice you haven't set limits. The .5 cpu and 1G mem are the default limits. Do you think it even needs that much? It's idle at the moment obviously, but currently it is only using .1 cpu and 100M of mem. Any sense of what it might need at peak?

**Comment by aorin** [comment]
I don't know how much it needs exactly, I guess we have to see how much it's using when the test users start using it but yeah the default limits seem unnecessary high. When I visited the site, the usage was about 30m cpu and 175Mi memory. I decreased the limits to 100m and and 500Mi for now

**Comment by mikkohei13** [comment]
Basic functionality seems ok: login, saving, viewing, logging out.
