### ISSUE TITLE
Show which times and locations have data

### ISSUE THREAD

**Issue by mikkohei13** [luomus/lintuasemasovellus#81]
While being in shorthand editing modal (see attached image), I would like to see which of these selections (combinations of tyyppi and sijainti) have data and how much (e.g. how many rows), without checking each of them manually.

![Image](https://github.com/user-attachments/assets/f7c855b7-2977-48e6-9899-ea2301a214e7)

**Comment by aorin** [comment]
@mikkohei13 can be tested here: https://lintuasema-dev-new.2.rahtiapp.fi/#/daydetails/11.10.2022 

Now the type select shows the location count and the location select shows the observation period count.

**Comment by mikkohei13** [comment]
Looks good, tested with Firefox.
