### ISSUE TITLE
Päivitys rikkoo sivun

### ISSUE THREAD

**Issue by sinikala** [luomus/lintuasemasovellus#9]
Sivun päivittäminen rikkoo ainakin päivälistauksen (näytä päivät) sekä yksittäisen päivän näkymän. Jälkimmäisen taustalla Observersin oleminen undefined.

**Comment by teemuoksanen** [comment]
Koitin selvitellä tätä. Vaikuttaisi siltä, että state ei ole jotenkin ajan tasalla - kaikki sivukyselyt kiertävät loginin kautta?

**Comment by LinAksel** [comment]
Päivitysongelma on nyt korjattu, ja käyttäjä ohjataan etusivulle hajoamisen sijaan.
